apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-ai-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-ai-inference
  template:
    metadata:
      labels:
        app: enterprise-ai-inference
    spec:
      containers:
        - name: enterprise-ai-inference
          image: enterprise-ai-inference:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
